/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AboutUs {
    }
    interface AppRoot {
    }
    interface ImageCarousel {
    }
    interface NavBar {
    }
    interface OurMusic {
    }
    interface SimpleSlider {
        "showStatus": boolean;
    }
    interface SocialMedia {
    }
}
declare global {
    interface HTMLAboutUsElement extends Components.AboutUs, HTMLStencilElement {
    }
    var HTMLAboutUsElement: {
        prototype: HTMLAboutUsElement;
        new (): HTMLAboutUsElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLImageCarouselElement extends Components.ImageCarousel, HTMLStencilElement {
    }
    var HTMLImageCarouselElement: {
        prototype: HTMLImageCarouselElement;
        new (): HTMLImageCarouselElement;
    };
    interface HTMLNavBarElement extends Components.NavBar, HTMLStencilElement {
    }
    var HTMLNavBarElement: {
        prototype: HTMLNavBarElement;
        new (): HTMLNavBarElement;
    };
    interface HTMLOurMusicElement extends Components.OurMusic, HTMLStencilElement {
    }
    var HTMLOurMusicElement: {
        prototype: HTMLOurMusicElement;
        new (): HTMLOurMusicElement;
    };
    interface HTMLSimpleSliderElement extends Components.SimpleSlider, HTMLStencilElement {
    }
    var HTMLSimpleSliderElement: {
        prototype: HTMLSimpleSliderElement;
        new (): HTMLSimpleSliderElement;
    };
    interface HTMLSocialMediaElement extends Components.SocialMedia, HTMLStencilElement {
    }
    var HTMLSocialMediaElement: {
        prototype: HTMLSocialMediaElement;
        new (): HTMLSocialMediaElement;
    };
    interface HTMLElementTagNameMap {
        "about-us": HTMLAboutUsElement;
        "app-root": HTMLAppRootElement;
        "image-carousel": HTMLImageCarouselElement;
        "nav-bar": HTMLNavBarElement;
        "our-music": HTMLOurMusicElement;
        "simple-slider": HTMLSimpleSliderElement;
        "social-media": HTMLSocialMediaElement;
    }
}
declare namespace LocalJSX {
    interface AboutUs {
    }
    interface AppRoot {
    }
    interface ImageCarousel {
    }
    interface NavBar {
    }
    interface OurMusic {
    }
    interface SimpleSlider {
        "showStatus"?: boolean;
    }
    interface SocialMedia {
    }
    interface IntrinsicElements {
        "about-us": AboutUs;
        "app-root": AppRoot;
        "image-carousel": ImageCarousel;
        "nav-bar": NavBar;
        "our-music": OurMusic;
        "simple-slider": SimpleSlider;
        "social-media": SocialMedia;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "about-us": LocalJSX.AboutUs & JSXBase.HTMLAttributes<HTMLAboutUsElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "image-carousel": LocalJSX.ImageCarousel & JSXBase.HTMLAttributes<HTMLImageCarouselElement>;
            "nav-bar": LocalJSX.NavBar & JSXBase.HTMLAttributes<HTMLNavBarElement>;
            "our-music": LocalJSX.OurMusic & JSXBase.HTMLAttributes<HTMLOurMusicElement>;
            "simple-slider": LocalJSX.SimpleSlider & JSXBase.HTMLAttributes<HTMLSimpleSliderElement>;
            "social-media": LocalJSX.SocialMedia & JSXBase.HTMLAttributes<HTMLSocialMediaElement>;
        }
    }
}
